#---------------------------------------------------#
## 配置文件需要放置在 $HOME/.config/clash/*.yaml

## 这份文件是clashX的基础配置文件，请尽量新建配置文件进行修改。
## ！！！只有这份文件的端口设置会随ClashX启动生效

## 如果您不知道如何操作，请参阅 官方Github文档 https://github.com/Dreamacro/clash/blob/dev/README.md
#---------------------------------------------------#

# (HTTP and SOCKS5 in one port)
mixed-port: 7890
# RESTful API for clash
external-controller: 127.0.0.1:9090
allow-lan: false
mode: rule
log-level: warning

proxies:
  - name: "BillZeus"
    type: ss
    server: zeus.yuanbin.me
    port: 8883
    cipher: aes-128-gcm
    password: "breakGFW!"
    # udp: trues

  - name: "NasLocal-Socks5"
    type: socks5
    server: 192.168.31.3
    port: 8881  

  - name: "Nas-Local-SS"
    type: ss
    server: 192.168.31.3
    port: 8883
    cipher: aes-128-gcm
    password: "breakGFW!"
    # udp: trues  

  - name: "Nas-LocalHttps"
    type: http
    server: 192.168.31.3
    port: 8882
    username: billryan
    password: bill123nayr
    tls: true 

  - name: "bwg2"
    type: vmess
    server: freedom.bwg2.alphalabx.com
    port: 443
    uuid: aa51e3de-e083-4bc4-87af-335cb6c2b101
    cipher: none
    alterId: 32
    udp: true
    tls: true

  - name: "bwgzg"
    type: vmess
    server: freedom.bwgzg.alphalabx.com
    port: 443
    uuid: aa51e3de-e083-4bc4-87af-335cb6c2b101
    cipher: none
    alterId: 32
    udp: true
    tls: true

  - name: "moscow_jh"
    type: vmess
    server: freedom.jh.alphalabx.com
    port: 443
    uuid: d4eddae3-a1fb-4783-9aba-05e5a45be81c
    alterId: 32
    cipher: none
    udp: true
    tls: true    

proxy-groups:
  - name: "Proxy"
    type: url-test
    proxies:
      - GaoZeus
      - NasLocal-Socks5
      - Nas-Local-SS
      - Nas-LocalHttps
    # tolerance: 150
    # lazy: true
    url: 'http://www.gstatic.com/generate_204'
    interval: 300

  - name: "Proxy-Foreign"
    type: url-test
    proxies:
      - bwg2
      - bwgzg
      - moscow_jh
    # tolerance: 150
    # lazy: true
    url: 'http://www.gstatic.com/generate_204'
    interval: 300

rules:
  - DOMAIN-SUFFIX,istore.app,Proxy
  - DOMAIN,youtube4kdownloader.com,Proxy
  - DOMAIN-SUFFIX,chinadigitaltimes.net,Proxy-Foreign
  - DOMAIN-SUFFIX,chinadigitaltimes.net,Proxy
  - DOMAIN-SUFFIX,rsshub.app,Proxy
  - DOMAIN-SUFFIX,emojiall.com,Proxy
  - DOMAIN-SUFFIX,graph.org,Proxy
  - DOMAIN-SUFFIX,macosicons.com,Proxy
  - DOMAIN-SUFFIX,substack.com,Proxy
  - DOMAIN-SUFFIX,qitabbs.com,Proxy
  - DOMAIN-SUFFIX,zhainanredian.com,Proxy
  - DOMAIN-SUFFIX,goyelang.net,Proxy
  - DOMAIN-SUFFIX,vipfanhao.com,Proxy
  - DOMAIN-SUFFIX,2047.one,Proxy
  - DOMAIN-SUFFIX,ikmjx.com,Proxy
  - DOMAIN-SUFFIX,everia.club,Proxy
  - DOMAIN-SUFFIX,twitter.com,Proxy
  - DOMAIN-SUFFIX,telegra.ph,Proxy
  - DOMAIN-SUFFIX,youtube.com,Proxy
  - DOMAIN-KEYWORD,github,Proxy
  - DOMAIN,www.ahhhhfs.com,Proxy
  - DOMAIN-SUFFIX,google.com,Proxy
  - DOMAIN-KEYWORD,v2ex,Proxy
  - DOMAIN-SUFFIX,zendesk.com,Proxy
  - DOMAIN-SUFFIX,pinterest.es,Proxy
  - DOMAIN-SUFFIX,github.com,Proxy
  - DOMAIN-SUFFIX,hifini.com,Proxy
  - DOMAIN-SUFFIX,mypikpak.com,Proxy
  - GEOIP,CN,DIRECT
  - MATCH,DIRECT
  
  
